.TH "ESTIMATE-REMAINING" "1" "2021-05-13" "Geek Central" "Render-Useful Collection"

.SH NAME
estimate\-remaining \- estimate time remaining for rendering an animation in
.UR https://blender.org/
Blender
.UE .

.SH SYNOPSIS
.BR estimate\-remaining " [" «options» "...] " «frames\-output\-dir» " " «final\-frame\-nr»

.SH DESCRIPTION
.PP
.B estimate\-remaining
is a command-line tool which, given a directory into which rendered frames
are being saved as individual image files and the expected number of the final
frame, will examine the timestamps on the most recent saved frames to estimate
when the render will finish.

The script automatically recognizes a common file extension and the number of digits
in the file names: the name part before the extension should consist entirely of decimal
digits, and it should always be the same number of digits.
.I E.g.
names could be something like
.BR 0001.png ", " 0002.png
etc.

.SH OPTIONS

.TP
.B \-\-nr\-frames=«sample-size»
the number of most recent frames to examine the timestamps on. If omitted,
the default is 6.

.TP
.B \-\-estimate\-error|\-e
indcates that the output should include an estimate of the uncertainty
in the completion time.

.SH EXAMPLES
.B estimate\-remaining frames/ 1600

Shows an estimate of how long it will take for frame number 1600 to appear
in directory
.B frames/
for a render currently in progress.

.B estimate\-remaining \-\-nr-frames=12 \-e frames/ 1600

Same as above, except base the estimate on the last 12 frames rendered, and
also include an estimate of the uncertainty in the completion time.
