.TH "EXT-FILES" "1" "2021-05-13" "Geek Central" "Render-Useful Collection"

.SH NAME
ext\-files \- analysis of external dependencies of
.UR https://blender.org/
Blender
.UE
documents.

.SH SYNOPSIS
.B ext\-files [«options»...] «blend-file»

.SH DESCRIPTION
.P
.B ext\-files
is a command-line tool that scans a
.UR https://blender.org/
Blender
.UE
document to find all referenced external files. Such external files
may be images used as textures, fonts, sounds, libraries, or text files
used as Open Shading Language or IESNA-LM-63 (a.k.a. “IES”) lighting
parameter definitions.

.B ext\-files
works by invoking Blender in batch mode and using its Python API to perform
an analysis of the given document.

.SH OPTIONS

.TP
.B \-\-blender=«blender»
specifies the path to the Blender executable. Defaults to
searching for the name “blender” in your
.BR PATH .

.TP
.B \-\-full
specifies that details about the dependencies are to be
printed in JSON format. Otherwise only the file paths are
printed, one to a line.

.TP
.B \-\-presence
also includes the status of each external file, whether it
could be found (and read) or not.

.TP
.B \-\-test-missing
don’t produce any output, but return a success/failure exit
status if
.B «blend\-file»
does/does not have any missing dependencies respectively. Incompatible with
the
.BR \-\-full ,
.B \-\-presence
or
.B \-\-test\-requires
options.

.TP
.B \-\-test\-requires=«depfile»
don’t produce any output, but return a success/failure exit
status if
.B «blend\-file»
does/does not have
.B «depfile»
as a dependency respectively. Incompatible with the
.BR \-\-full ,
.B --presence
or
.B \-\-test-missing
options.

.SH EXAMPLES

.RS
ext-files --presence test.blend
.RE

Reports on the dependencies of
.BR test.blend ,
including their status as “present” or “missing”.

.RS
.nf
IFS=$'\en'
for f in $(find . -name \e*.blend  -not -exec ext-files --test-missing {} ';' -print); do
    echo
    echo "${f}:"
    ext-files --presence "$f" | grep -v '^present\e:'
done
.fi
.RE

Scans the current directory (and all subdirectories) for
.B .blend
files which have missing dependencies (assumes there is at least one), and prints
a listing of those missing dependencies for each such file.
