.TH "INCOMPRESS" "1" "2022-09-03" "Geek Central" "Render-Useful Collection"

.SH NAME
incompress - decompress and recompress
.UR https://blender.org/
Blender
.UE
documents.

.SH SYNOPSIS
\fBincompress\fR [\fIoptions\fR ...] \fIin-blend-file\fR \fI[out-blend-file]\fR

.SH DESCRIPTION
.P
.B incompress
is a command-line tool that can copy a
.UR https://blender.org/
Blender
.UE
document and change its compression format. Prior to Blender 3.0, such
documents could be uncompressed or compressed in GZip format. In Blender 3.0,
the compression format for new documents has been changed to
.UR https://facebook.github.io/zstd/
Zstandard
.UE .
.B incompress
supports conversion between all three formats, though Zstandard compression/decompression
requires the installation of the
.UR https://github.com/sergey-dryabzhinsky/python-zstd
python3-zstd
.UE
module.

.SH OPTIONS

.TP
\fB--compression=\fIformat\fR
specifies the compression format to be used for writing \fBout-blend-file\fR.
\fIformat\fR can be one of \fBnone\fR (uncompressed), \fBgzip\fR or \fBzstd\fR.
If omitted, the default is \fBnone\fR.

.TP
\fB--info\fR
causes \fBincompress\fR to output a line reporting the compression
format of \fIin-blend-file\fR.

.TP
\fB--inplace\fR
specifies that the output file is to replace the input file. This is done
safely, so in case of any errors the input file should remain untouched.
This option requires the installation of the
.UR https://github.com/ldo/python_linuxfs
linuxfs
.UE
module.

.TP
\fB--keep-times\fR
specifies that the output file is to be given the same last access/modified
timestamps as the input file.

.SH EXAMPLES

.RS
\fBincompress in.blend out.blend\fR
.RE

Copies \fBin.blend\fR to \fBout.blend\fR, ensuring that the output
is uncompressed.

.RS
\fBincompress --compression=gzip in.blend out.blend\fR
.RE

Copies \fBin.blend\fR to \fBout.blend\fR, ensuring that the output
is compressed in GZip format.

.RS
\fBincompress --compression=zstd --inplace file.blend\fR
.RE

Ensures that \fBfile.blend\fR is compressed in Zstd format.

.RS
\fBincompress --info in.blend\fR
.RE

Reports on the compression state of \fBin.blend\fR and does nothing further
with it.
