#!/usr/bin/python3
#+
# This script packs up a specified .blend file, along with its
# external dependencies, into any of various archive formats, for
# convenient transfer to another location. Invoke it as follows:
#
#     packup-blend [options...] blendfile archivefile
#
# where blendfile is the name of the .blend file to pack up,
# archivefile is the name of the archive file to create. The filename
# extension of the archivefile indicates the archive format to create:
# this can be .zip, .7z, .tar, or the various common compressed
# versions of the latter.
#
# Valid options are
#    --blender=blender
#          specifies the path to the Blender executable. Defaults to
#          searching for the name “blender” in your PATH.
#     --verbose
#         display various progress messages
#
# External commands needed:
#     ext-files (part of the same render-useful package that includes packup-blend);
#     tar, 7z and/or zip.
#
# Copyright 2017-2018 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
# Licensed under CC-BY-SA <http://creativecommons.org/licenses/by-sa/4.0/>.
#-

import sys
import os
import enum
import subprocess
import json
import getopt

#+
# Archive types
#-

@enum.unique
class DOUBLE_DASH(enum.Enum) :
    "where to put a “--” on an archiver’s command line to prevent interpretation" \
    " of filenames that might begin with dashes as options."
    NOT_SUPPORTED = 0
    BEFORE_FILES = 1
    AFTER_SUFFIX_ARG = 2
#end DOUBLE_DASH

archivers = \
    { # for constructing archive-creation commands
        "tar" :
            {
                "cmd" : ("tar", "--create", "--dereference"),
                "cmd_suffix" : ("--file",),
                "double_dash" : DOUBLE_DASH.AFTER_SUFFIX_ARG,
                "subtype_opts" :
                    lambda subtype :
                        {
                            "bzip2" : ("--bzip2",),
                            "gzip" : ("--gzip",),
                            "xz" : ("--xz",),
                        }[subtype],
                "verbose" : ("--verbose",),
            },
        "zip" :
            {
                "cmd" : ("zip",),
                "double_dash" : DOUBLE_DASH.NOT_SUPPORTED,
                "verbose" : ("--verbose",),
            },
        "7z" :
            {
                "cmd" : ("7z", "a"),
                "double_dash" : DOUBLE_DASH.BEFORE_FILES,
                "verbose" : (),
                "quiet" : ("-bd",), # not really that much difference
            },
    }

file_exts = \
    { # choose appropriate archiver depending on output filename extension
        ".tar" : {"type" : "tar"},
        ".tar.bz2" : {"type" : "tar", "subtype" : "bzip2"},
        ".tar.gz" : {"type" : "tar", "subtype" : "gzip"},
        ".tar.xz" : {"type" : "tar", "subtype" : "xz"},
        ".tbz2" : {"type" : "tar", "subtype" : "bzip2"},
        ".tgz" : {"type" : "tar", "subtype" : "gzip"},
        ".txz" : {"type" : "tar", "subtype" : "xz"},
        ".zip" : {"type" : "zip"},
        ".7z" : {"type" : "7z"},
    }

#+
# Mainline
#-

blender = None
verbose = False
opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "v",
    ["blender=", "verbose"]
  )
for keyword, value in opts :
    if keyword == "--blender" :
        blender = value
    elif keyword == "-v" or keyword == "--verbose" :
        verbose = True
    #end if
#end for
if len(args) != 2 :
    raise getopt.GetoptError("need exactly 2 args: the input .blend file and output archive file name")
#end if
blendfile, archivefile = args
if not blendfile.endswith(".blend") :
    raise getopt.GetoptError("doesn’t end with .blend: %s" % repr(blendfile))
#end if
if not os.path.isfile(blendfile) :
    raise getopt.GetoptError("cannot find %s" % repr(blendfile))
#end if
nr_dots = 0
max_dots = max((len(k.split(".")) - 1) for k in file_exts)
dotpos = len(archivefile)
while True :
    if nr_dots == max_dots :
        raise getopt.GetoptError("unrecognized extension: %s" % repr(archivefile))
        break
    #end if
    nr_dots += 1
    dotpos2 = archivefile[:dotpos].rfind(".")
    if dotpos2 >= 0 :
        dotpos = dotpos2
    else :
        dotpos = dotpos2
    #end if
    if dotpos < 0 and nr_dots == 1 :
        raise getopt.GetoptError("doesn’t have an extension: %s" % repr(archivefile))
    #end if
    if dotpos >= 0 :
        file_ext = archivefile[dotpos:]
        if file_ext in file_exts :
            break
    #end if
#end while

cmd = "ext-files"
try_parent_dir = False
while True :
    try :
        deps = subprocess.check_output \
          (
            args = (cmd,) + ((), ("--blender=%s" % blender,))[blender != None] + ("--full", blendfile),
            universal_newlines = True,
          )
        break
    except FileNotFoundError :
        if try_parent_dir :
            raise
        #end if
    #end try
    cmd = os.path.join(os.path.split(sys.argv[0])[0], cmd)
    try_parent_dir = True
#end while
deps = json.loads(deps)
deps = set(i["filepath"] for i in sum((v for v in deps.values()), []))
  # set instead of list/tuple to remove any duplicates

blendfilepath = os.path.abspath(blendfile)
archivefilepath = os.path.abspath(archivefile)
parent_dir = os.path.split(blendfilepath)[0]
choose = file_exts[file_ext]
archiver = archivers[choose["type"]]

args = list(archiver["cmd"])
if verbose :
    if "verbose" in archiver :
        args.extend(list(archiver["verbose"]))
    #end if
else :
    if "quiet" in archiver :
        args.extend(list(archiver["quiet"]))
    #end if
#end if
if "subtype" in choose :
    args.extend(list(archiver["subtype_opts"](choose["subtype"])))
#end if
if "cmd_suffix" in archiver :
    args.extend(list(archiver["cmd_suffix"]))
#end if
if archiver["double_dash"] == DOUBLE_DASH.BEFORE_FILES :
    args.append("--")
#end if
args.append(archivefilepath)
if archiver["double_dash"] == DOUBLE_DASH.AFTER_SUFFIX_ARG :
    args.append("--")
#end if
args.append(os.path.split(blendfilepath)[1])
  # .blend file is always at root of unpacked directory tree
for item in sorted(deps) : # might as well include dependencies in consistent order
    if item.startswith("//") and not item.startswith("//../") :
        item = item[2:]
        args.append \
          (
                ("", "./")
                    [archiver["double_dash"] == DOUBLE_DASH.NOT_SUPPORTED and item.startswith("-")]
            +
                item
          )
          # keep relative paths relative in archive
    else :
        # ignore up-level paths, absolute paths and paths with no leading “/”
        sys.stderr.write("%s: ignoring %s\n" % (sys.argv[0], repr(item)))
    #end if
#end for

subprocess.check_call \
  (
    args = args,
    cwd = parent_dir, # for correct interpretation of relative paths
  )
