.TH "PACKUP-BLEND" "1" "2021-05-13" "Geek Central" "Render-Useful Collection"

.SH NAME
packup\-blend \- package a
.UR https://blender.org/
Blender
.UE
document and external dependencies into an archive file.

.SH SYNOPSIS
.BR packup\-blend " [" «options» "...] " «blend\-file» " " «archive\-file»

.SH DESCRIPTION
.PP
.B packup\-blend
is a command-line tool that creates an archive file in any of various
common formats, containing the given
.B «blend\-file»
and any external files (such as image textures and fonts) that it needs.

The external files are only included if they are referenced by relative
paths (beginning with
.RB “ // "”) in the " .blend
file) in the same containing directory or a subdirectory. Up-level dependencies,
and dependencies referenced by absolute paths, are ignored.

The format for
.B «archive\-file»
is automatically chosen depending on the filename extension it is given:
.BR .tar ", " .7z ", " .zip .
Common compressed variants of
.B .tar
format are also recognized:
.BR .tar.bz2 ", " .tbz2 ", " .tar.gz ", " .tgz ", " .tar.xz ", " .txz .

.SH OPTIONS

.TP
.B \-\-blender=«blender»
specifies the path to the Blender executable. Defaults to searching for
the name “blender” in your
.BR PATH .

.TP
.B \-\-verbose
displays various progress messages.

.SH BUGS

Perhaps ignored dependencies should trigger an error instead of being silently omitted.

.SH EXTERNAL PROGRAMS NEEDED

Besides Blender itself, the
.BR ext-files (1)
command (part of this same package) is used to collect the dependencies,
and the standard
.BR tar ", " 7z " and " zip
utilities are used to create the respective archive formats.

.SH SEE ALSO
.BR 7z "(1), " ext-files "(1), " tar "(1), " zip "(1)"
