.TH "RENUMBER-FRAMES" "1" "2021-05-20" "Geek Central" "Render-Useful Collection"

.SH NAME
renumber-frames - reassign frame numbers to sequences of frame files

.SH SYNOPSIS
\fBrenumber-frames\fR [\fIoptions\fR...] \fIop fromdir fromrange todir torange\fR

.SH DESCRIPTION
.P
\fBrenumber-frames\fR is a command-line tool that does bulk renaming of files
with numerically-assigned names like \fB0001.png\fR, \fB0002.png\fR
etc, giving them new names in a specified range. The files can be renamed in place,
copied or moved to a new directory under the new names, or just symlinked or hardlinked
to the new directory, depending on \fIop\fR.

The script automatically recognizes a common file extension and the number of digits
in the file names: the name part before the extension should consist entirely of decimal
digits, and it should always be the same number of digits. Unless otherwise specified,
the new names will have the same number of digits as the old ones.

.SH ARGUMENTS

.TP
.I op
The operation to perform:
.RS
.TP
.B copy
The files are copied under the new names.

.TP
.B move
The files are renamed under the new names.

.TP
.B symlink
The files are symlinked under the new names.

.TP
.B hardlink
The files are hardlinked under the new names.
.RE

.TP
.I fromdir
The directory containing the frame files to operate on.

.TP
.I fromrange
The \fIrange-spec\fR (see below) specifying the range of files to operate on.

.TP
.I todir
The directory in which to put the renamed files.

.TP
.I torange
The \fIrange-spec\fR (see below) giving the new names for the files.

.PP
A \fIrange-spec\fR takes one of the following forms, where \fIlo\fR and
\fIhi\fR are positive decimal integers:

.TP
.IR lo - hi
.RI "-- frame numbers " lo " to " hi " inclusive"

.TP
.IR lo : hi
.RI "-- frame numbers " lo " to (" hi " - 1) inclusive"

.TP
.IR lo + count
.RI "-- frame numbers " lo " to (" lo " + " count " - 1) inclusive"

.TP
.I lo
-- start at frame number \fIlo\fR and increment as necessary. Only
permitted for the \fItorange\fR; successive frame numbers will be
assigned from this starting point for corresponding frames in
\fIfromrange\fR.

.PP
For move operations, \fIfromrange\fR and \fItorange\fR may overlap,
even if \fIfromdir\fR and \fItodir\fR are the same, provided that
frames will not be given the same names as existing frames that
are not being renamed.

.SH OPTIONS

.TP
\fB--digits=\fIto_digits\fR
If specified, then the new file names will have this number
of digits in their names, instead of the same number as the
original files.

.TP
\fB--dry-run\fR
If specified, then no actual copy/move/link operations will
be performed, only the messages will be output. Useful for
confirming that the operation will produce the correct results
before turning it loose on the filesystem.

.SH EXAMPLES

.RS
\fBrenumber-frames copy fromdir/ 1-100 todir/ 200\fR
.RE

Copies frames numbered 1 to 100 (inclusive) from \fBfromdir/\fR to
\fBtodir/\fR, renumbering them to start from 200.

.RS
\fBrenumber-frames --digits=5 move framesdir/ 1-1000 framesdir/ 1\fR
.RE

Renames the frames within the same directory while keeping the same frame numbers,
setting the number of digits to 5.
