.TH "ZEROUSERS" "1" "2021-05-21" "Geek Central" "Render-Useful Collection"

.SH NAME
zerousers - display and clean out orphaned data blocks from a
.UR https://blender.org/
Blender
.UE
document.

.SH SYNOPSIS
\fBzerousers\fR [\fIoptions\fR ...] \fIblend-file\fR

.SH DESCRIPTION
.P
.B zerousers
is a command-line tool that examines a
.UR https://blender.org/
Blender
.UE
document, looking for data blocks with a “user count” (reference
count) of zero. Such blocks are not supposed to be included when
Blender saves a document. But it seems its current cleanup algorithm
does not consider blocks being referenced by a block being omitted
from the save; even though their counts might go to zero, they get
saved with the document regardless.

However, if the document is reloaded and saved again, these blocks will be
deleted. But not any blocks that they were referencing for which the user
count has now gone to zero. And so on.

So what \fBzerousers\fR does is keep reloading and saving the document,
until all such blocks have disappeared.

.SH OPTIONS

.TP
\fB--blender=\fIblender\fR
specifies the path to the Blender executable. Defaults to
searching for the name “blender” in your \fBPATH\fR.

.TP
\fB--clear\fR
specifies that orphaned blocks are actually to be cleared from
the document. Without this option, they are merely displayed.

.SH NOTES

Blender has the concept of \fIfake users\fR. That is, the user count
of a block is increased by one by clicking an icon, just to ensure the block
will not be deleted from the document, even if it is not explicitly used
anywhere. Since the “fake” user is included in the user count,
\fBzerousers\fR will not delete such a block.

.SH EXAMPLES

.RS
\fBzerousers test.blend\fR
.RE

Shows a list of orphaned blocks from the file \fBtest.blend\fR.

.RS
\fBzerousers --clear test.blend\fR
.RE

Clears out orphaned blocks from the file \fBtest.blend\fR.
